FROM node:22-alpine
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN corepack enable && pnpm install --prod --frozen-lockfile
COPY apps/ticket-server ./apps/ticket-server
COPY apps/ticket-web ./apps/ticket-web
ENV PORT=8787
EXPOSE 8787
CMD ["node", "apps/ticket-server/main.mjs"]
