import {createRequire} from 'node:module';import {mkdirSync,mkdtempSync,rmSync,writeFileSync} from 'node:fs';import path from 'node:path';import os from 'node:os';import assert from 'node:assert/strict';import {createApp} from '../apps/server/main.mjs';
const require=createRequire(import.meta.url);const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const dir=mkdtempSync(path.join(os.tmpdir(),'arena-browser-'));const config={httpPort:0,mqttPort:0,operatorPin:'12345678',ticketServerUrl:'https://tickets.example.test',devices:[1,2,3,4].map(n=>({id:`gun-00${n}`,key:`test-${n}`,name:`プレイヤー${n}`,team:n<3?'A':'B',shooterId:n}))};
const app=await createApp({config,demo:true,dataDir:dir,bind:'127.0.0.1'});const base=`http://127.0.0.1:${app.httpServer.address().port}`;let browser;const errors=[];
try {browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext({viewport:{width:1180,height:820},hasTouch:true});const admin=await context.newPage();admin.on('pageerror',e=>errors.push(e.message));await admin.goto(base);await admin.waitForFunction(()=>document.querySelector('[data-ticket-destination="operator"]').href.startsWith('https://tickets.example.test/operator?game='));await admin.locator('#pin').fill(config.operatorPin);await admin.getByRole('button',{name:'ログイン',exact:true}).click();await admin.locator('#dashboard').waitFor({state:'visible'});
 const display=await context.newPage();display.on('pageerror',e=>errors.push(e.message));await display.goto(base+'/display');await display.locator('#prepare').click();await admin.waitForFunction(()=>document.getElementById('readiness').textContent.includes('準備完了')&&document.getElementById('readiness').textContent.includes('4/4'));
 await admin.locator('[data-media=rules]').click();await display.waitForFunction(()=>document.getElementById('overlayTitle').textContent==='赤外線チーム対戦');
 await admin.locator('[data-media=video]').click();await display.waitForFunction(()=>{const v=document.getElementById('video');return !v.hidden&&!v.paused&&v.currentTime>.2&&v.videoWidth===1280});
 assert.ok(Math.abs(await display.locator('#video').evaluate(v=>v.duration)-35)<.2);
 await admin.locator('[data-media=score]').click();await display.waitForFunction(()=>document.getElementById('video').hidden);
 await admin.locator('[data-action=start]').click();await admin.waitForFunction(()=>document.getElementById('phase').textContent==='試合中');await admin.locator('#demoReceiver').selectOption('all');await admin.locator('#demoHit').click();await admin.waitForFunction(()=>document.querySelectorAll('.hp')[2].textContent==='75 HP');assert.equal(app.game.player('gun-003').hp,75);
 await admin.waitForFunction(()=>{const text=document.querySelectorAll('.meta')[2].textContent;return text.includes('前:1 左:1 右:1');});assert.equal(app.game.player('gun-003').hp,75);assert.equal(app.game.player('gun-003').damageFeedback.duration_ms,180);
 for(const [rx,hp]of [['rx2',50],['rx3',25]]){await admin.locator('#demoReceiver').selectOption(rx);await admin.locator('#demoHit').click();await admin.waitForFunction(hp=>document.querySelectorAll('.hp')[2].textContent===hp+' HP',hp);await admin.waitForFunction(rx=>document.querySelectorAll('.meta')[2].textContent.includes((rx==='rx2'?'左:':'右:')+'2'),rx);assert.equal(app.game.player('gun-003').lastReceiver,rx);}
 mkdirSync('artifacts/browser',{recursive:true});await admin.screenshot({path:'artifacts/browser/operator.png',fullPage:true});await display.screenshot({path:'artifacts/browser/projector.png'});
 await admin.locator('[data-action=pause]').click();await admin.waitForFunction(()=>document.getElementById('phase').textContent==='一時停止');assert.equal(app.game.s.phase,'PAUSED');
 await admin.setViewportSize({width:768,height:1024});await admin.screenshot({path:'artifacts/browser/ipad-portrait.png',fullPage:true});assert.equal(await admin.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 assert.deepEqual(errors,[]);writeFileSync('artifacts/browser/result.json',JSON.stringify({revision:'0.6',checkedAt:new Date().toISOString(),passed:true,browser:'Edge headless; iPad-sized viewport (not physical iPad)',checks:['login','projector readiness','four MQTT simulators','rules slides','35-second H264 MP4 playback at 1280x720','return from video to score','countdown ACK','three receiver MQTT reports: HP100 to75 once','individual rx2/rx3 hits','PC-issued 180ms feedback','receiver counters and last receiver','pause','portrait no horizontal overflow'],errors},null,2));console.log('Browser E2E: PASS');
}finally{await browser?.close();await app.close();if(path.dirname(dir)===os.tmpdir()&&path.basename(dir).startsWith('arena-browser-'))rmSync(dir,{recursive:true,force:true});}
