import {createRequire} from 'node:module';import {mkdirSync,readdirSync,writeFileSync,readFileSync} from 'node:fs';import {spawnSync} from 'node:child_process';import path from 'node:path';import {createHash} from 'node:crypto';import {slides} from '../apps/web/rules-content.js';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const tool=process.env.FFMPEG||path.resolve('.tools/ffmpeg',readdirSync('.tools/ffmpeg').find(s=>s.endsWith('essentials_build')),'bin/ffmpeg.exe');
mkdirSync('assets/build',{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true});
try{const page=await browser.newPage({viewport:{width:1280,height:720},deviceScaleFactor:1});for(let i=0;i<slides.length;i++){
 const [title,...lines]=slides[i];await page.setContent(`<!doctype html><html lang="ja"><meta charset="utf-8"><style>*{box-sizing:border-box}body{margin:0;background:#0a1626;color:#f5f8fb;font-family:'Yu Gothic','Meiryo',sans-serif;padding:62px 76px}header{display:flex;justify-content:space-between;align-items:center;color:#8da4bd;font-size:22px;letter-spacing:3px}.teams{display:flex;gap:8px}.teams b{padding:8px 18px;background:#075370;color:#74e4fa;border-radius:6px}.teams b+b{background:#633b0b;color:#ffd085}h1{font-size:62px;letter-spacing:2px;margin:102px 0 40px;font-weight:700}p{font-size:30px;line-height:1.8;margin:8px 0;color:#d2dfed}footer{position:absolute;left:76px;right:76px;bottom:48px;display:flex;align-items:center;gap:12px;color:#8da4bd;font-size:18px}i{height:5px;width:68px;border-radius:6px;background:#273b52}i.on{background:#57d8f1}span{margin-left:auto}</style><header>AKASHI / IR ARENA <div class="teams"><b>A · 2人</b><b>B · 2人</b></div></header><h1>${title}</h1>${lines.map(t=>`<p>${t}</p>`).join('')}<footer>${slides.map((_,j)=>`<i class="${j<=i?'on':''}"></i>`).join('')}<span>参加前にご確認ください　${i+1} / ${slides.length}</span></footer></html>`);await page.screenshot({path:`assets/build/rule-${String(i).padStart(2,'0')}.png`});}}
finally{await browser.close();}
const args=['-y','-framerate','1/7','-i','rule-%02d.png','-f','lavfi','-i','anullsrc=channel_layout=stereo:sample_rate=48000','-t','35','-vf','fps=25,format=yuv420p','-c:v','libx264','-preset','medium','-crf','20','-c:a','aac','-b:a','96k','-movflags','+faststart','../rules.mp4'];
const result=spawnSync(tool,args,{cwd:'assets/build',windowsHide:true,encoding:'utf8'});if(result.status!==0)throw Error(result.stderr);
writeFileSync('assets/render-report.json',JSON.stringify({durationSeconds:35,size:[1280,720],video:'H.264 yuv420p 25fps',audio:'AAC stereo silent; no narration/music',slides:5,sha256:createHash('sha256').update(readFileSync('assets/rules.mp4')).digest('hex'),toolSource:'https://www.ffmpeg.org/download.html'},null,2));console.log('rules.mp4 rendered: 35 seconds, 5 captions, silent audio');
